security:
  always_authenticate_before_granting: true

  encoders:
    App\Classes\User:
      algorithm: sha512

  role_hierarchy:
    ROLE_DATASOURCE_CREATOR: ROLE_DATASOURCE_MANAGER
    ROLE_MATCHING_LIST_CREATOR: ROLE_MATCHING_LIST_MANAGER
    ROLE_PROCESSOR_CREATOR: ROLE_PROCESSOR_MANAGER
    ROLE_SEARCH_PAGE_CREATOR: ROLE_SEARCH_PAGE_MANAGER
    ROLE_BOOST_QUERY_CREATOR: ROLE_BOOST_QUERY_MANAGER
    ROLE_PARAMETER_CREATOR: ROLE_PARAMETER_MANAGER
    ROLE_ADMIN: [ROLE_INDEX_MANAGER, ROLE_DATASOURCE_CREATOR, ROLE_MATCHING_LIST_CREATOR, ROLE_PROCESSOR_CREATOR, ROLE_SEARCH_PAGE_CREATOR, ROLE_BOOST_QUERY_CREATOR, ROLE_ANALYTICS_USER, ROLE_LOGS_VIEWER, ROLE_BACKUP_USER, ROLE_CONSOLE_USER, ROLE_AUTOPROMOTE_USER, ROLE_PARAMETER_CREATOR]

  providers:
    app_users:
      id: hevea_user_provider

  firewalls:
    main:
      logout_on_user_change: true
      pattern: ^/
      form_login:
        provider: app_users
        csrf_token_generator: security.csrf.token_manager
        login_path: login
        check_path: login
      anonymous:    true
      logout:
        path:   logout
        target: login

  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/_profiler, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/_wdt, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/test, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: ROLE_ADMIN }